"""Users and MF Portfolio table

Revision ID: 2e3ad5c25629
Revises: 
Create Date: 2020-12-30 14:55:57.045479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3ad5c25629'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mf_portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fund_name', sa.String(length=480), nullable=True),
    sa.Column('folio_num', sa.String(length=480), nullable=True),
    sa.Column('as_on_date', sa.DateTime(), nullable=True),
    sa.Column('cub', sa.Float(precision=128), nullable=True),
    sa.Column('nav', sa.Float(precision=128), nullable=True),
    sa.Column('total_investment', sa.Float(precision=128), nullable=True),
    sa.Column('investing_since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mf_portfolio_email'), 'mf_portfolio', ['email'], unique=False)
    op.create_index(op.f('ix_mf_portfolio_folio_num'), 'mf_portfolio', ['folio_num'], unique=False)
    op.create_index(op.f('ix_mf_portfolio_fund_name'), 'mf_portfolio', ['fund_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_confirmed'), 'user', ['confirmed'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_index(op.f('ix_user_user_type'), 'user', ['user_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_type'), table_name='user')
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_confirmed'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_mf_portfolio_fund_name'), table_name='mf_portfolio')
    op.drop_index(op.f('ix_mf_portfolio_folio_num'), table_name='mf_portfolio')
    op.drop_index(op.f('ix_mf_portfolio_email'), table_name='mf_portfolio')
    op.drop_table('mf_portfolio')
    # ### end Alembic commands ###
