"""Added time-zone to users

Revision ID: ec50a9ea8463
Revises: 2e3ad5c25629
Create Date: 2020-12-30 16:30:27.916212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec50a9ea8463'
down_revision = '2e3ad5c25629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_timezone'), 'user', ['timezone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_timezone'), table_name='user')
    op.drop_column('user', 'timezone')
    # ### end Alembic commands ###
